default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: "mitsubishi"
  username: root
  password: "0000"
development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
